language: node_js
node_js:
  - "0.10"

# whitelist
branches:
  only:
    - master

after_script: NODE_ENV=test istanbul cover _mocha --report lcovonly -- -R spec test/test.js && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage